// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd7rKXcZS4YOHs3ptP7DOVnFDaEoUxqLg',
    appId: '1:626622535340:web:1a58abe9f517b2344ef109',
    messagingSenderId: '626622535340',
    projectId: 'logaa-d733f',
    authDomain: 'logaa-d733f.firebaseapp.com',
    storageBucket: 'logaa-d733f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylfpIxt7U3lzzMp_nkkYpQQ_-2go2iu0',
    appId: '1:626622535340:android:856f62204e97e7cd4ef109',
    messagingSenderId: '626622535340',
    projectId: 'logaa-d733f',
    storageBucket: 'logaa-d733f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir7iukvQNN48qdL0Jrtt1PdAWgebrGg0',
    appId: '1:626622535340:ios:1f357d4e889804f44ef109',
    messagingSenderId: '626622535340',
    projectId: 'logaa-d733f',
    storageBucket: 'logaa-d733f.appspot.com',
    iosBundleId: 'com.example.logaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAir7iukvQNN48qdL0Jrtt1PdAWgebrGg0',
    appId: '1:626622535340:ios:c0fc003f17729afc4ef109',
    messagingSenderId: '626622535340',
    projectId: 'logaa-d733f',
    storageBucket: 'logaa-d733f.appspot.com',
    iosBundleId: 'com.example.logaa.RunnerTests',
  );
}
